# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecao',
            old_name='time',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='selecao',
            name='pontuacao',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selecao',
            name='sigla',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
