# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0002_auto_20170919_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol1', models.IntegerField(default=0)),
                ('gol2', models.IntegerField(default=0)),
                ('estadio', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='selecao',
            options={'verbose_name_plural': 'Selecoes'},
        ),
        migrations.AddField(
            model_name='partida',
            name='time1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='bolao.selecao'),
        ),
        migrations.AddField(
            model_name='partida',
            name='time2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='bolao.selecao'),
        ),
    ]
