# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_auto_20170926_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='sigla',
            field=models.CharField(max_length=3),
        ),
    ]
