# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0005_auto_20171017_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecao',
            name='pontuacao',
        ),
    ]
