# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0008_auto_20171031_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='gols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='time_vencedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Vencedor', to='bolao.selecao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aposta',
            name='aposta_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Partidas', to='bolao.Partida'),
        ),
    ]
