# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0009_auto_20171031_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='gols',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='time_vencedor',
        ),
        migrations.AddField(
            model_name='aposta',
            name='gols_time1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aposta',
            name='gols_time2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aposta',
            name='aposta_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.Partida'),
        ),
    ]
