# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0014_aposta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='valor',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
