# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0018_auto_20171110_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='aposta_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.Partida'),
        ),
    ]
