# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0019_auto_20171110_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='user',
        ),
    ]
