# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0022_remove_aposta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
